# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a289911ef7026e219614a3100069c0ccc0be9b745b9515c994af6163741ef2f8ca5a36e8b4323996f6bc68dbeec36d5b5f82d5ed8baea610c3f844a397cd97

test:
  secret_key_base: 4a7bafcab6d975937ac1fa84604961e8f2bd0834ecdc0ba26e4a5fedbf596cb492f600774e762542cc614c0c7735786b9f69e2457f7d88612130030b3442bcdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
